# Generated by Django 5.1.3 on 2024-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('commercial', 'Commercial'), ('hotel', 'Hotel'), ('rent', 'Rent')], max_length=20, null=True),
        ),
    ]
